### PR TITLE
issue 94

### PR DESCRIPTION
**Pull request by bazmatic**
Added missing named parameter "image". This parameter is being passed positionally as well but this does fix the bug and allow the script to complete.

### CODE REVIEW

**Comment by inquiring-minds-ai** [comment]
This fixes the issue initially on Colab, but if the Generate Animation Frames script is interrupted before it completes, then the Colab Session needs restarted for the script to work again.

**Comment by SchmitzAndrew** [comment]
@bazmatic ,

I've had the exact same error as you and was very excited to see your pull request. 
Unfortunately, I still get this error after making your change:
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-28-2fe179bfbcf4>](https://localhost:8080/#) in <module>
    155         tot_variations -= curr_variation_count  # only generate variations we still need
    156         for _ in range(tot_variations):
--> 157             img = get_variations_w_init(prompt, init_image, image=init_image, start_schedule=(1-image_consistency))[0]
    158             save_frame(
    159                 img,

3 frames
[/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

TypeError: __call__() got an unexpected keyword argument 'init_image'
```

This is my implementation of your solution: 
```
        for _ in range(tot_variations):
            img = get_variations_w_init(prompt, init_image, image=init_image, start_schedule=(1-image_consistency))[0]
```

Please let me know if I'm missing anything. I am using the library on Google Colab.

**Comment by hfllr** [comment]
I get that error as well, even with no session interruption.
A merge/ fix would be highly appreciated!

**Comment by dmarx** [comment]
fixed in 0.1.8 release

**Pull request closed without merging**
